### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by VineyS** [apurv-r/discord-together#2]
`link = togetherControl.create_link(ctx.author.voice.channel.id, 'betrayal')` and `link =  togetherControl.create_link(ctx.author.voice.channel.id, 'fishing')`  in README.md is to be updated to  

`link = await togetherControl.create_link(ctx.author.voice.channel.id, 'betrayal')`

`link = await togetherControl.create_link(ctx.author.voice.channel.id, 'fishing')`

as these are now coroutine

**Comment by VineyS** [comment]
Since, Its just a minor issue . it could be updated when a new update launches on this awesome project. Thank You apur-v for making this :smile:

**Comment by apurv-r** [comment]
Thanks for spotting that out! I'll definitely fix that in the next release.
