### ISSUE TITLE
Request for ask away game implementation 

### ISSUE THREAD

**Issue by pogrammar** [apurv-r/discord-together#9]
This was a request for the Implementation of **Ask away**, the newly released and announced game.

You already must be in the discord games lab server. The announcement regarding this is [Here](https://discord.com/channels/831646372519346186/831646372519346189/994250879781830667)

Thank you ☺️

**Comment by apurv-r** [comment]
Hi! I've seen the announcement and have already made a quick little update on the package's discord support server regarding it. I will be updating the package with support for the new activity by tomorrow.

**Comment by apurv-r** [comment]
The package has been updated to add support for 'Ask Away'. Kindly update to `v1.2.6` to use the new activity. 

Thanks.
